spring.application.name=patientservice
server.port=8082
# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/patient_service
spring.datasource.username=admin
spring.datasource.password=secret_patient_pass
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.idle-timeout=30000

# RABBIT
app.broker.queue.person.bind=person.bind

# COMMON CONFIG
# App Security
app.security.token.secret=53253355
app.security.token.issuer=userservice
app.security.roles.admin=ADMIN
app.security.roles.patient=PATIENT
app.security.roles.doctor=DOCTOR

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.password=secret
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin

# JPA & Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.globally_quoted_identifiers=true
spring.jpa.properties.hibernate.format_sql=true

# Logging
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Server
server.forward-headers-strategy=framework

# SpringDoc
springdoc.api-docs.enabled=true

spring.cloud.openfeign.httpclient.hc5.enabled=true
