spring.application.name=config-server
server.port=8888

spring.cloud.config.server.git.uri=https://github.com/Samuel-Pinheiro-C-Lopes/health-connect-configurations
spring.cloud.config.server.git.username=Samuel-Pinheiro-C-Lopes
spring.cloud.config.server.git.password=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