spring.application.name=config-server
server.port=8888

spring.cloud.config.server.git.uri=https://github.com/Samuel-Pinheiro-C-Lopes/health-connect-configurations
spring.cloud.config.server.git.username=Samuel-Pinheiro-C-Lopes
spring.cloud.config.server.git.password=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