spring.application.name=doctorservice
server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5433/doctor_service
spring.datasource.username=admin
spring.datasource.password=secret_doctor_pass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# RabbitMQ
app.broker.queue.person.bind=person.bind

spring.config.import=optional:configserver:http://localhost:8888


